### ISSUE TITLE
syncing set of subfolders?

### ISSUE THREAD

**Issue by tonnerkiller** [qcif/nextcloud-sync-cron#1]
Hi, thank you very much for this script. Is there a way to select only certain subfolders for syncing? In some cases the whole data might be too much for a local machine.

**Comment by hoylen** [comment]
Does setting the `remote` URL in the config file to a URL that contains a path work?

The script is just a wrapper on the _Nextcloud command line client_ whose "nextcloudurl" argument seems to accept paths. See the example under the "Credential Handling" section of the [Nextcloud command line client](https://docs.nextcloud.com/desktop/2.5/advancedusage.html#nextcloud-command-line-client)  document.

**Comment by tonnerkiller** [comment]
Thank you for your answer. I tried all day to edit the script to get the option -exclude running only to find out that you cannot exclude certain folders but only patterns...
Also for the server url I cannot give subfolders as this leads to an error. Maybe the --unsyncedfolders option would do but it's gotten late... the sad thing is you find hardly any docu about it...

**Comment by tonnerkiller** [comment]
I have to correct myself, it seems to be working with `--unsyncedfolders`

**Comment by tonnerkiller** [comment]
made a pull request. Might be clumsy code, but this is the first time I work with a shell script, so please be patient.

**Comment by hoylen** [comment]
If the `--unsyncedfolders` works for you then that is good. It has the obvious limitation that you must know _beforehand_ all the directories you don't want. And if you create a new directory you must _remember_ to add it to the script's configuration file, otherwise it will get included which might not be what you want.

Thanks for the pull request.
