### ISSUE TITLE
Mixed Indentation

### ISSUE THREAD

**Issue by so-rose** [qcif/nextcloud-sync-cron#12]
It seems that there is mixed indentation throughout the script, which makes it difficult to contribute.

## Example

For example, lines 168-172 in [cf3fc63](https://github.com/qcif/nextcloud-sync-cron/blob/cf3fc639e2bc016e695c1bfae246482f62cd75cd/nextcloud-sync-cron.sh) use 4 spaces to indent, while 173-180 uses a mixture of tabs and spaces.

## Potential FIx

Whichever is preferred, I suggest a .editorconfig file to enforce. This can be automatically read by most editors and implemented automatically, so that nobody ever has to question it again!

This is how the .editorconfig file would look for 4-space indentation.

```
# EditorConfig is awesome: http://EditorConfig.org

# Top-Most EditorConfig file
root = true

# Unix-style newlines with a newline ending every file
[*]
end_of_line = lf
insert_final_newline = true
indent_style = space
indent_size = 4
```

I'm happy to make a merge request making tabs/spaces consistent, and implementing the associated .editorconfig, if this (or if tabs!) is desired :)

**Comment by hoylen** [comment]
Thanks for pointing that out.

I have now added your _.editorconfig_ file and converted the tabs to spaces. Using 4 space indent, since that was what the original file was using.
