### ISSUE TITLE
sync fails because "davpath" is not a valid option of nextcloudcmd anymore

### ISSUE THREAD

**Issue by benjamindahl** [qcif/nextcloud-sync-cron#17]
I'm using nextcloudcmd version 3.5.4 where --davpath option is now --path.
I had to change line 559 in the script from davpath to path and then everything worked as expected.

best regards
benny

**Comment by hoylen** [comment]
Thank you very much for the report Benny.

It is good you can edit the script to make it work for your setup. We'll have to think of a way to update the script for users using v3.5.4, but have it still work for users on older version of _nextcloudcmd_.

**Comment by hoylen** [comment]
The script has been updated to use the new name `--path`, by this pull request: https://github.com/qcif/nextcloud-sync-cron/pulls
