### ISSUE TITLE
syntax error 

### ISSUE THREAD

**Issue by cbshopper** [qcif/nextcloud-sync-cron#6]
there is an syntax error in line 543: 
UNSYNCEDFOLDERS_OPTION=
if [ -n "$UNSYNCEDFOLDERS" ]; then
  UNSYNCEDFOLDERS_OPTION="--unsyncfolders \"$UNSYNCEDFOLDERS\""
fi

shoud be "--unsyncedfolders" 

can you please adapt the code?
Thank you!

**Comment by hoylen** [comment]
Thanks for reporting this.

It has now been fixed in version 1.4.1 on GitHub (use `./nextcloud-sync-cron.sh -V` to check which version you have).
